spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/test_db
    user-name: root
    password: 123456
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'